version: "3.2"

services:
  api-backend:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.rest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3.10.0-rc.3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: Riven
      RABBITMQ_DEFAULT_PASS: testpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - redis

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: Riven
      GF_SECURITY_ADMIN_USER: Riven

  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    depends_on:
      - grafana
